version: '3'
services:
  shastic_challenge:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    links:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      APP_ENV: production
      DATABASE_URL: mysql2://root:pass@mysql/poro_production
      PORO_URL: http://localhost:3000
    stdin_open: true
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    ports:
      - 3306:3306
    volumes:
      - ./:/app
    environment:
      MYSQL_ROOT_PASSWORD: pass
